### ISSUE TITLE
Create Final Video for Codebase

### ISSUE THREAD

**Issue by salonishah01** [salonishah01/CSC510-FALL23-P28-Project3#11]
## Goal

The goal of this issue is to create a final video demonstrating the functionality of the codebase. This video will serve as a comprehensive overview and can be used for promotional or documentation purposes.

## Guidelines

The video should provide a clear and engaging presentation of the code's features.
Include relevant explanations and annotations to enhance understanding.
Keep the video length appropriate for the target audience.
Ensure audio quality and clarity in any voiceovers or annotations.

## Steps

1. **Review Codebase:**
Familiarize yourself with the key features and functionalities of the code.

2. **Script Creation:**
Create a script outlining the content and flow of the video.

3. **Recording:**
Record the video, ensuring a steady and clear presentation.

4. **Editing:**
Edit the video for clarity, conciseness, and overall quality.

5. **Annotations (if applicable):**
Add explanatory annotations or voiceovers to guide viewers through the code.

6. **Review:**
Review the final video to ensure it aligns with the project's goals.

**Comment by rushilv20** [comment]
I and Sahil recorded the video. And the YouTube link for the same is now in README file.
