### ISSUE TITLE
Implement Watchlist Feature

### ISSUE THREAD

**Issue by salonishah01** [salonishah01/CSC510-FALL23-P28-Project3#4]
Users should be able to create and manage watchlists to track the prices of specific items.

**Comment by sahilchanglani** [comment]
To implement a watchlist feature, we can start by designing a database structure to store user data, items, and watchlists. Enable user authentication for secure access and create a user-friendly dashboard for watchlist management. Implement functionality for users to easily add items. Set up a background process to regularly update item prices and store this information, along with historical data, in the database. 

Allow customization of watchlists, including notes and categorization, and enable users to share watchlists collaboratively. Ensure mobile accessibility and implement HTTPS and secure coding practices for data protection. Collect and address user feedback, comply with regulations, and conduct thorough testing before deploying the application. Monitor system performance and conduct regular maintenance to address issues and improve the overall user experience.

**Comment by sahilchanglani** [comment]
Just pushed the initial implementation of the watchlist feature! 🚀 Started by designing the database structure to store user data, items, and watchlists. Enabled user authentication for secure access and created a slick dashboard for easy watchlist management. Users can now add items effortlessly, and I've set up a background process for regular price updates, storing both current and historical data in the database.

**Comment by salonishah01** [comment]
Great progress! I checked out the changes, and everything seems solid so far. I noticed you've allowed customization of watchlists, including notes and categorization—nice touch. Also, the collaborative watchlist sharing feature is a game-changer. Mobile accessibility is working smoothly, and kudos for implementing HTTPS and secure coding practices. Are there any challenges during the process?

**Comment by sahilchanglani** [comment]
Thanks! It's been fairly smooth. Had to optimize the background process for price updates to keep things snappy. Thorough testing helped catch a few bugs before deploying. Still, ongoing monitoring and maintenance are in place for continuous improvement.

**Comment by salonishah01** [comment]
Sounds like a solid execution! I'll do a deeper dive into the codebase and run some tests on my end. If everything checks out, we can consider this feature ready for production. Well done on getting this implemented in just a few conversations!

**Comment by sahilchanglani** [comment]
Appreciate it! Looking forward to your feedback. Let me know if you need anything else. Excited to see this watchlist feature in action!
