### ISSUE TITLE
Design a Chrome Extension for Price Comparison

### ISSUE THREAD

**Issue by salonishah01** [salonishah01/CSC510-FALL23-P28-Project3#8]
**Background:**

As online shopping continues to grow in popularity, users often find themselves navigating multiple websites to compare prices before making a purchase. To streamline this process and enhance the user experience, we propose the development of a Chrome extension that enables users to compare prices across different websites seamlessly.

**Objectives:**

- Create a Chrome extension that can extract and display product prices from various e-commerce websites.
- Provide a user-friendly interface for comparing prices side-by-side.
- Allow users to easily toggle between websites and products for quick comparisons.

**Features:**

**Automatic Price Extraction:**
Implement a mechanism to automatically extract product prices from popular e-commerce websites.

**User Interface:**
Design an intuitive and visually appealing interface for displaying prices.
Include options for users to customize the display based on their preferences.

**Multi-Website Support:**
Ensure compatibility with a diverse range of e-commerce platforms to maximize utility.

**Product Search:**
Integrate search functionality that allows users to quickly find and compare specific products.

**Price History:**
Consider implementing a feature to track and display price history for selected products.

**Browser Compatibility:**
Ensure compatibility with the latest versions of Google Chrome.

**Comment by sahilchanglani** [comment]
The Chrome extension has been successfully integrated into our web application under the extensions folder.
