### ISSUE TITLE
Create Small GIFs Illustrating Features

### ISSUE THREAD

**Issue by salonishah01** [salonishah01/CSC510-FALL23-P28-Project3#9]
## Goal

The goal of this issue is to create small GIFs demonstrating the working of various features. These GIFs will be used for visual representation and documentation purposes.

## Guidelines

- GIFs should be concise and focused on showcasing one feature at a time.
- Keep the GIF file size reasonable for web use.
- Ensure clarity and visibility in each GIF.

## Steps

1. Identify features to be covered.
2. Create GIFs for each feature.
3. Upload the GIFs to a designated folder in the repository.

**Comment by sahilchanglani** [comment]
Let's add some funny gifs related to low prices or something like that?!

**Comment by rushilv20** [comment]
> Let's add some funny gifs related to low prices or something like that?!

Yes, I am thinking about one from Shark tank or something. Let me see

**Comment by sahilchanglani** [comment]
Sounds good. I have added some in the gifs folder.

**Comment by rushilv20** [comment]
Added!
